// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpqcjajxunfmvzlewmvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwcWNqYWp4dW5mbXZ6bGV3bXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMTQyNjksImV4cCI6MjA1OTc5MDI2OX0.tPA1d8ChD4ULUQ-RV1MMO16li6Yn95z--lIMg-MKhZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);